# Generated by Django 3.1.3 on 2020-11-07 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('bio', models.CharField(blank=True, default='', max_length=1000)),
                ('photo_url', models.TextField(default='')),
                ('age', models.IntegerField(default=0)),
                ('share_age', models.BooleanField(default=True)),
                ('expertise', models.TextField(default='')),
                ('gender', models.CharField(choices=[('0', 'male'), ('1', 'female'), ('2', 'do not want to share')], default='friendly', max_length=100)),
                ('interests', models.TextField(default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
