# Generated by Django 3.1.3 on 2020-11-15 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201114_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('conference', '0'), ('instutution', '1'), ('journal', '2')], default='conference', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('seeking for collaborators', '0'), ('open for collaborators', '1'), ('in progress', '2'), ('done', '3')], default='seeking for collaborators', max_length=100),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('projects', models.ManyToManyField(to='api.Project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'ordering': ['project'],
            },
        ),
    ]
