# Generated by Django 3.1.3 on 2020-11-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201115_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('deadline', models.DateField()),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('journal submission', '0'), ('academic conference', '1'), ('funded project', '2')], max_length=50)),
                ('url', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
