# Generated by Django 3.1.3 on 2020-11-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201116_2324'),
        ('api', '0003_auto_20201115_2248'),
    ]

    operations = [
    ]
