# Generated by Django 3.1.3 on 2020-11-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201121_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='events',
            field=models.ManyToManyField(to='api.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('0', 'journal submission'), ('1', 'academic conference'), ('2', 'funded project')], max_length=50),
        ),
    ]
