# Generated by Django 3.1.3 on 2020-12-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201208_1543'),
        ('api', '0009_auto_20201208_2042'),
    ]

    operations = [
    ]
