# Generated by Django 3.1.4 on 2020-12-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201219_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_raters',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
    ]
