#!/bin/bash

echo "starting to create virtual environment and install packages"
python -m venv orgenv

source orgenv/bin/activate

pip install -r requirements.txt
echo "finished to create virtual environment and install packages"

echo "propagating changes you make to your models (adding a field, deleting a model, etc.) into your database schema. "
python manage.py makemigrations

python manage.py migrate

echo "starting to run the server"

python manage.py runserver
