#!/bin/sh
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

#prepare python environment
source backend/orgenv/Scripts/activate

#run pylint
LANG=en_US.UTF-8 PYTHONIOENCODING=utf8 pylint --rcfile=.pylintrc backend

if [ $? -eq 0 ]
then
  echo "Successfully finished static code analysis with pylint"
  exit 0
else
  echo "There are errors in static code analysis with pylint so please check your files" >&2
  exit 0
fi


#run bandit
bandit -r backend

if [ $? -eq 0 ]
then
  echo "Successfully finished code security check with bandit"
  exit 0
else
  echo "There are errors in code security check with bandit so please check your files" >&2
  exit 0
fi

