const config = {
  API_URL: process.env.REACT_APP_API_URL,
  Login_Path : "/login",
  Register_Path: "/register",
  Login_Url : "/api/auth/",
  Register_Url : "/api/register/",
  Event_Creation_Path : "/create-event",
  Event_Creation_Url : "/api/events/",
  Create_Project_Path :"/create-project",
  Create_Project_Url : "/api/projects/",
  Homepage_Path: "/",
  Projectpage_Path: "/project",
  Projectpage_url: "/api/projects/",
  Profilepage_url: "/api/profiles/",
  Edit_Profile_Url :"/api/profiles/",
  Edit_Project_Url : "/api/projects/", 
  User_Path: "/api/users/",
  Event_Path: "/events",
  Follow_url:"/api/follow/",
  Follow_request_url:"/api/follow_request/",
  Milestone_url:"/api/milestones/",
  OwnMilestoneUrl : "/api/milestones/get_user_milestones/",
  Issue_Milestone_Path : "/issue-milestone",
  Profille_Page_Path : "/profile"
}
export default config;
